// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmDk5Lq49d4BRnCAHNdBO1yLgAA9gsrVg',
    appId: '1:63779992613:web:ffab203606b1050af6bbcc',
    messagingSenderId: '63779992613',
    projectId: 'noteefy-app',
    authDomain: 'noteefy-app.firebaseapp.com',
    databaseURL: 'https://noteefy-app-default-rtdb.firebaseio.com',
    storageBucket: 'noteefy-app.appspot.com',
    measurementId: 'G-CZG5DXJBCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTg-0DLyY2YskSV9VwRX-8k2FnazAyHs',
    appId: '1:63779992613:android:d4bdf8ea91a53684f6bbcc',
    messagingSenderId: '63779992613',
    projectId: 'noteefy-app',
    databaseURL: 'https://noteefy-app-default-rtdb.firebaseio.com',
    storageBucket: 'noteefy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh2Es8oYlQSydaLRfaHR3oUT_Hx5nnotg',
    appId: '1:63779992613:ios:cd26dba54f8a54bff6bbcc',
    messagingSenderId: '63779992613',
    projectId: 'noteefy-app',
    databaseURL: 'https://noteefy-app-default-rtdb.firebaseio.com',
    storageBucket: 'noteefy-app.appspot.com',
    iosClientId: '63779992613-mahocf01o62caudq1d4grvd97quhsso8.apps.googleusercontent.com',
    iosBundleId: 'com.fibbee.noteefy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh2Es8oYlQSydaLRfaHR3oUT_Hx5nnotg',
    appId: '1:63779992613:ios:cd26dba54f8a54bff6bbcc',
    messagingSenderId: '63779992613',
    projectId: 'noteefy-app',
    databaseURL: 'https://noteefy-app-default-rtdb.firebaseio.com',
    storageBucket: 'noteefy-app.appspot.com',
    iosClientId: '63779992613-mahocf01o62caudq1d4grvd97quhsso8.apps.googleusercontent.com',
    iosBundleId: 'com.fibbee.noteefy',
  );
}
